version: "3.9"
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: ruby_app
    volumes:
      - ./myapp:/myapp
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    restart: unless-stopped

  nginx:
    image: nginx
    volumes:
      - ./myapp:/myapp
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    ports:
      - 80:80
