version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ruby_learn
    volumes:
      - ./my_ruby:/my_ruby
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    restart: unless-stopped

  nginx:
    image: nginx
    volumes:
      - ./my_ruby:/my_ruby
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    ports:
      - 80:80
